import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Chat from '../components/Chat/Chat'
import styles from '../styles/Home.module.css'

export async function getServerSideProps() {
  const res = await fetch(`http://localhost:3000/api/hello`)
  const data = await res.json()
  return { props: { data } }
}

type Test = {
  data: {
    name: string
    owner: string
  };
};

const Test: NextPage<Test> = (props: Test) => {
  const { data: { owner } } = props;

  return (
    <div className={styles.container}>
      <Head>
        <title>Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Chat owner={owner} />
      </main>
    </div>
  )
}

export default Test


